// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorPreferences } from "./EditorPreferences";
import type { GenerationSettings } from "./GenerationSettings";
import type { LlmSettings } from "./LlmSettings";

/**
 * 画面（`src-tauri`）が持つ設定一式。
 */
export type AppSettings = { llm: LlmSettings, generation: GenerationSettings, editor: EditorPreferences, 
/**
 * 最近開いた作品フォルダ。新しい順、重複なし、最大 [`MAX_RECENT_PROJECTS`] 件。
 */
recent_projects: Array<string>, };
