// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * 作品フォルダへの変更案。
 */
export type ChangeSet = { summary: string, 
/**
 * ファイルへの変更。適用の順は並び順に頼らず、ゴミ箱へ移す → 書く。
 */
files: Array<FileChange>, 
/**
 * この変更案を作った作品フォルダ（正規化した絶対パス）。生成中に別の作品へ開き直したとき、
 * 前の作品の変更案を書き込まないよう、適用時に照合する。
 */
project_root: string, };
