// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type ChangeSet = { summary: string, files: Array<FileChange>, 
/**
 * この変更案を作った作品フォルダ（正規化した絶対パス）。生成中に別の作品へ開き直したとき、
 * 前の作品の変更案を書き込まないよう、適用時に照合する。
 */
project_root: string, };
