// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScenePlan } from "./ScenePlan";

/**
 * `plot/chapters/<NN>.md` の front matter。
 */
export type ChapterMeta = { 
/**
 * 章題。
 */
title: string, 
/**
 * シーン構成。並び順がそのままシーンの順序になる。
 */
scenes?: Array<ScenePlan>, };
