// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `characters/<id>.md` の front matter。
 */
export type CharacterMeta = { 
/**
 * 表示名。
 */
name: string, 
/**
 * 読み仮名（任意）。
 */
reading?: string | null, 
/**
 * 役回り（主人公、探偵、など）。
 */
role: string, 
/**
 * 一言紹介。
 */
summary: string, 
/**
 * 表示順（任意）。
 */
order?: number | null, };
