// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandErrorKind } from "./CommandErrorKind";

/**
 * Tauri コマンドが返すエラー。`message` は利用者にそのまま見せられる。
 */
export type CommandError = { kind: CommandErrorKind, message: string, };
