// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * エラーの種別。
 */
export type CommandErrorKind = "conflict" | "not_found" | "invalid_input" | "llm" | "cancelled" | "io" | "internal";
