// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditableDocument } from "./EditableDocument";

/**
 * 画面へ返す、項目に分けた文書。[`kataribe_project::LoadedDocument`] の `hash` を文字列にしたもの。
 */
export type DocumentFile = { document: EditableDocument, 
/**
 * 読み込んだ時点のファイル全体のハッシュ（16 進小文字）。保存時の競合検出に使う。
 */
hash: string, 
/**
 * 人物資料・章立てなのに front matter を解釈できず、文字列として返したときの理由。
 */
parse_error: string | null, };
