// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterMeta } from "./ChapterMeta";
import type { CharacterMeta } from "./CharacterMeta";

/**
 * 画面で編集する文書。人物資料と章立ては front matter を項目に分け、それ以外は文字列のまま扱う。
 */
export type EditableDocument = { "kind": "text", 
/**
 * ファイル全体の内容。
 */
content: string, } | { "kind": "character", 
/**
 * front matter の項目。
 */
meta: CharacterMeta, 
/**
 * 本文。
 */
body: string, } | { "kind": "chapter", 
/**
 * front matter の項目。
 */
meta: ChapterMeta, 
/**
 * この章のストーリーライン（本文）。
 */
body: string, };
