// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontStyle } from "./FontStyle";

/**
 * エディタ画面の見え方の設定。
 */
export type EditorPreferences = { 
/**
 * 縦書きかどうか。
 */
vertical: boolean, font_style: FontStyle, font_size: number, line_height: number, };
