// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationSettings } from "./GenerationSettings";
import type { LlmSettings } from "./LlmSettings";

/**
 * エンジンが使う設定一式。アプリはこれに画面の設定を足して同じファイルに保存する。
 */
export type EngineSettings = { llm: LlmSettings, generation: GenerationSettings, };
