// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RelPath } from "./RelPath";
import type { TrashedFile } from "./TrashedFile";

/**
 * 作品フォルダのファイルへの、1 つの変更。
 */
export type FileChange = { "kind": "write", 
/**
 * 書き込み先。
 */
path: RelPath, 
/**
 * 書き込む内容。
 */
content: string, 
/**
 * 変更前の内容。新規ファイルなら `None`。
 */
previous: string | null, 
/**
 * 変更前の内容のハッシュ。適用時に、その後の編集と競合していないか確かめる。
 */
base_hash: ContentHash | null, } | { "kind": "trash", 
/**
 * 移すもの。
 */
path: RelPath, 
/**
 * 移すファイルの一覧。今は `path` のファイル 1 つだけ。
 */
files: Array<TrashedFile>, };
