// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RelPath } from "./RelPath";
import type { TrashedFile } from "./TrashedFile";

/**
 * 作品フォルダのファイルへの、1 つの変更。
 */
export type FileChange = { "kind": "write", 
/**
 * 書き込み先。
 */
path: RelPath, 
/**
 * 書き込む内容。
 */
content: string, 
/**
 * 変更前の内容。新規ファイルなら `None`。
 */
previous: string | null, 
/**
 * 変更前の内容のハッシュ。適用時に、その後の編集と競合していないか確かめる。
 */
base_hash: ContentHash | null, } | { "kind": "trash", 
/**
 * 移すもの。
 */
path: RelPath, 
/**
 * 移すファイルの一覧。ファイルを移すときは `path` のファイル 1 つだけ。フォルダを移すときは、
 * フォルダの中のファイル全部（サブフォルダの下も含む。空のフォルダなら空）。適用するときは、
 * 今の中身がこの一覧と完全に一致しなければ競合にする（利用者が確かめた中身だけを移すため）。
 */
files: Array<TrashedFile>, } | { "kind": "move", 
/**
 * 移動元。
 */
from: RelPath, 
/**
 * 移動先。同じ変更案のゴミ箱や移動で空く場所を除いて、空いていなければならない。
 */
to: RelPath, } | { "kind": "expect", 
/**
 * 確かめるパス。
 */
path: RelPath, 
/**
 * そのファイルの今のハッシュ。`None` なら「何も無いこと」。
 */
base_hash: ContentHash | null, };
