// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RelPath } from "./RelPath";

export type FileChange = { path: RelPath, content: string, 
/**
 * 変更前の内容。新規ファイルなら `None`。
 */
previous: string | null, 
/**
 * 変更前の内容のハッシュ。適用時に、その後の編集と競合していないか確かめる。
 */
base_hash: ContentHash | null, };
