// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftUnit } from "./DraftUnit";

/**
 * 生成のしかたの設定。
 */
export type GenerationSettings = { draft_unit: DraftUnit, 
/**
 * 1 回の生成で書かせる目安の文字数。
 */
chars_per_call: number, 
/**
 * モデルに渡せる文脈の長さ（トークン）。
 */
context_tokens: number, temperature: number, 
/**
 * 本文を書いたあとに推敲パスをかけるか。
 */
polish: boolean, 
/**
 * 品質チェックで重大な問題が見つかったときの再生成回数。
 */
quality_retries: number, 
/**
 * 推論モデルの「思考」を止める。ローカル LLM では思考に出力の上限を使い切って
 * 本文が空になることがあるため、既定で止める。クラウドの API でエラーになる場合は切る。
 */
disable_thinking: boolean, };
