// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoticeLevel } from "./NoticeLevel";

export type GenerationEvent = { "kind": "step_started", label: string, index: number, total: number, } | { "kind": "content", text: string, } | { "kind": "reasoning", text: string, } | { "kind": "step_finished", prompt_tokens: number | null, completion_tokens: number | null, elapsed_ms: number, } | { "kind": "notice", level: NoticeLevel, message: string, };
