// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面の選択肢とプロンプトに使うジャンル。
 */
export type GenrePreset = { id: string, label: string, description: string, };
