// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 検出する問題点の種類。
 */
export type IssueKind = "meta_commentary" | "markdown_artifact" | "foreign_script" | "repeated_sentence" | "repeated_phrase" | "monotonous_endings" | "too_short" | "too_long" | "unbalanced_brackets";
