// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmProvider } from "./LlmProvider";

/**
 * LLM への接続設定。API キーは OS の資格情報ストアに別に保存する。
 */
export type LlmSettings = { provider: LlmProvider, 
/**
 * OpenAI 互換 API のベース URL。
 */
base_url: string, 
/**
 * OpenAI 互換 API のモデル。
 */
model: string, 
/**
 * Claude Code の `claude` コマンド（PATH に無ければ実行ファイルの場所）。空なら `claude`。
 */
claude_command: string, 
/**
 * Claude Code のモデル（`sonnet`・`opus`・`haiku` など）。空なら `sonnet`。
 *
 * 接続先を切り替えても、それぞれのモデルの指定を失わないよう `model` と分けている。
 */
claude_model: string, };
