// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LLM サーバーへの接続設定。API キーは OS の資格情報ストアに別に保存する。
 */
export type LlmSettings = { base_url: string, model: string, };
