// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

/**
 * `kataribe.yaml`（作品情報）。
 */
export type Manifest = { 
/**
 * 作品フォルダの形式バージョン。
 */
format: number, 
/**
 * 題名。
 */
title: string, 
/**
 * 著者名（任意）。
 */
author: string | null, 
/**
 * ジャンルプリセットの id。
 */
genre: string, 
/**
 * ジャンルの補足（任意）。
 */
genre_note: string | null, 
/**
 * 年齢区分。
 */
rating: Rating, 
/**
 * 目標総文字数。
 */
target_length: number, 
/**
 * 企画の種。最初に LLM へ渡す指示。
 */
idea: string, };
