// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`OpenAiCompatClient::list_models`](crate::OpenAiCompatClient::list_models) が返すモデル情報。
 */
export type ModelInfo = { id: string, 
/**
 * 文脈長。LM Studio の拡張 API から取得できたときだけ埋まる。
 */
context_length: number | null, };
