// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rating } from "./Rating";

/**
 * 新しい作品を作るときに利用者が入力する項目。
 */
export type NewProject = { title: string, author: string | null, genre: string, genre_note: string | null, rating: Rating, target_length: number, idea: string, };
