// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 足すシーンの設計。[`kataribe_project::ScenePlan`] から、足すときに決まる項目（id・ビート）を除いたもの。
 * id は足すときに、消したシーンの本文を引き継がないよう決める。
 */
export type NewScenePlan = { 
/**
 * シーン題。
 */
title: string, 
/**
 * このシーンの要約。
 */
summary: string, 
/**
 * 視点人物。
 */
pov: string | null, 
/**
 * 登場人物名の一覧。
 */
characters: Array<string>, 
/**
 * 場所。
 */
place: string | null, 
/**
 * 時間。
 */
time: string | null, 
/**
 * 目標文字数。
 */
target_chars: number | null, };
