// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlankLinePolicy } from "./BlankLinePolicy";

/**
 * [`normalize`] の挙動を切り替えるオプション。既定値はすべて有効、空行は保持する。
 *
 * 4 つの独立した整形項目を切り替えるための構造体であり、状態機械やビットフラグに
 * 置き換えても可読性は上がらないため、bool が多いという clippy の指摘は抑制する。
 */
export type NormalizeOptions = { 
/**
 * 段落頭を全角空白 1 つで字下げする。
 */
paragraph_indent: boolean, 
/**
 * `...`・`。。。`・`・・・`・単独の `…` を `……` にそろえる。
 */
ellipsis: boolean, 
/**
 * `--`・`——`・単独の `―` を `――` にそろえる。
 */
dash: boolean, 
/**
 * 半角の `!`/`?` を全角にし、直後に応じて全角空白を補う。
 */
fullwidth_marks: boolean, 
/**
 * 空行の扱い方。
 */
blank_lines: BlankLinePolicy, };
