// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryKind } from "./EntryKind";

export type OverviewEntry = { 
/**
 * 作品フォルダからの相対パス。ファイルに対応しない見出しは `None`。
 */
path: string | null, label: string, kind: EntryKind, exists: boolean, 
/**
 * 本文の文字数（ルビの読み・空白を除く）。
 */
chars: number, target_chars: number | null, 
/**
 * 読み込みや YAML の解析に失敗したときの説明。
 */
error: string | null, children: Array<OverviewEntry>, };
