// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewEntry } from "./OverviewEntry";
import type { SectionKind } from "./SectionKind";

export type OverviewSection = { kind: SectionKind, label: string, entries: Array<OverviewEntry>, };
