// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";
import type { EntryKind } from "./EntryKind";
import type { SceneId } from "./SceneId";

export type OverviewEntry = { 
/**
 * 作品フォルダからの相対パス。ファイルに対応しない見出しは `None`。
 */
path: string | null, label: string, kind: EntryKind, 
/**
 * 章に属する項目（章立て・本文の章見出し・シーンの本文）の章。本文の章見出しにはパスが無いので、
 * 画面が章を知るために持つ。
 */
chapter: ChapterId | null, 
/**
 * シーンの本文の項目のシーン。
 */
scene: SceneId | null, exists: boolean, 
/**
 * 本文の文字数（ルビの読み・空白を除く）。
 */
chars: number, target_chars: number | null, 
/**
 * 読み込みや YAML の解析に失敗したときの説明。
 */
error: string | null, children: Array<OverviewEntry>, };
