// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditableDocument } from "./EditableDocument";

/**
 * 文字列を、画面で編集する形に分けた結果。
 */
export type ParsedDocument = { 
/**
 * 分けた文書。
 */
document: EditableDocument, 
/**
 * 人物資料・章立てなのに項目に分けられず、[`EditableDocument::Text`] にしたときの理由
 * （[`LoadedDocument::parse_error`] と同じ）。
 */
parse_error: string | null, };
