// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepState } from "./StepState";
import type { Task } from "./Task";

export type PipelineStep = { task: Task, label: string, state: StepState, 
/**
 * `Blocked` のとき、先に済ませる必要がある工程の説明。
 */
blocked_by: string | null, };
