// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewSection } from "./OverviewSection";

export type ProjectOverview = { root: string, title: string, target_length: number, total_chars: number, sections: Array<OverviewSection>, };
