// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftUnit } from "./DraftUnit";
import type { LlmProvider } from "./LlmProvider";

/**
 * 作品ごとの設定。どの項目も省略でき、省略した項目はアプリ全体の設定を使う。
 */
export type ProjectSettings = { provider?: LlmProvider, 
/**
 * OpenAI 互換 API のモデル。
 */
model?: string, 
/**
 * Claude Code のモデル。
 */
claude_model?: string, draft_unit?: DraftUnit, chars_per_call?: number, context_tokens?: number, temperature?: number, polish?: boolean, quality_retries?: number, disable_thinking?: boolean, };
