// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSettings } from "./ProjectSettings";

/**
 * 画面へ返す作品の設定。保存するときの競合の検出に使う、読んだ時点の `kataribe.yaml` のハッシュも付ける。
 */
export type ProjectSettingsFile = { settings: ProjectSettings, 
/**
 * 読み込んだ時点の `kataribe.yaml` のハッシュ（16 進小文字）。
 */
hash: string, };
