// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QualityIssue } from "./QualityIssue";
import type { QualityMetrics } from "./QualityMetrics";
import type { TextStats } from "./TextStats";

/**
 * 品質指標と問題点をまとめた検査結果。
 */
export type QualityReport = { stats: TextStats, metrics: QualityMetrics, issues: Array<QualityIssue>, };
