// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueKind } from "./IssueKind";
import type { Severity } from "./Severity";

/**
 * 検出された 1 件の問題点。
 */
export type QualityIssue = { kind: IssueKind, severity: Severity, message: string, 
/**
 * 該当箇所の抜粋。行全体に関わる問題でない場合などは `None`。
 */
excerpt: string | null, };
