// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`analyze`] の挙動を切り替えるオプション。
 */
export type QualityOptions = { 
/**
 * 目標文字数。指定すると `too_short` / `too_long` を検出する。
 */
target_chars: number | null, };
