// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 機械的に測定できる品質指標。
 */
export type QualityMetrics = { 
/**
 * 「」『』の内側の文字数 / 全文字数。
 */
dialogue_ratio: number, 
/**
 * 漢字の数 / 全文字数。
 */
kanji_ratio: number, 
/**
 * 文（。！？と閉じ括弧で区切る）の平均文字数。
 */
average_sentence_length: number, 
/**
 * 地の文で、文末 2 文字が同じ文が連続した最大数。
 */
longest_same_ending_run: number, 
/**
 * 12 文字以上の同一部分文字列が 3 回以上出現する箇所が本文に占める割合。
 */
repeated_phrase_ratio: number, };
