// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 作品フォルダのルートを基準にした相対パス。
 *
 * 常に検証済みの状態でしか存在できない（`new` を通らない限り作れない）。
 */
export type RelPath = string;
