// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";

/**
 * 番号が変わる章。
 */
export type RenumberedChapter = { 
/**
 * 変わる前の番号。
 */
from: ChapterId, 
/**
 * 変わった後の番号。
 */
to: ChapterId, 
/**
 * 章題。章立てが読めなければ `None`。
 */
title: string | null, };
