// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";
import type { SceneId } from "./SceneId";

/**
 * 人物の名前を挙げているシーン。
 */
export type SceneReference = { 
/**
 * 章。
 */
chapter: ChapterId, 
/**
 * 章題。
 */
chapter_title: string, 
/**
 * シーン。
 */
scene: SceneId, 
/**
 * シーン題。
 */
scene_title: string, 
/**
 * 視点人物として挙げている。
 */
as_pov: boolean, 
/**
 * 登場人物として挙げている。
 */
as_character: boolean, };
