// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SceneId } from "./SceneId";

/**
 * 1 シーンぶんの設計（`plot/chapters/<NN>.md` の `scenes` の要素）。
 */
export type ScenePlan = { 
/**
 * シーン id。本文ファイル名にも使う。
 */
id: SceneId, 
/**
 * シーン題。
 */
title: string, 
/**
 * このシーンの要約。
 */
summary: string, 
/**
 * 視点人物（任意）。
 */
pov?: string | null, 
/**
 * 登場人物名の一覧。
 */
characters?: Array<string>, 
/**
 * 場所（任意）。
 */
place?: string | null, 
/**
 * 時間（任意）。
 */
time?: string | null, 
/**
 * 目標文字数（任意）。
 */
target_chars?: number | null, 
/**
 * ビート単位で生成したときの展開の一覧。
 */
beats?: Array<string>, };
