// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 本文を構成する断片。隣り合う [`Segment::Text`] は生成されない（常にまとめられる）。
 */
export type Segment = { "kind": "text", text: string, } | { "kind": "ruby", base: string, reading: string, } | { "kind": "emphasis", text: string, };
