// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeSet } from "./ChangeSet";
import type { RelPath } from "./RelPath";
import type { SceneReference } from "./SceneReference";

/**
 * 構成の操作の変更案と、利用者に見せる材料。
 */
export type StructurePlan = { 
/**
 * 作る変更案。作品フォルダを開いている `Project` のものとして印が付いている。
 */
change_set: ChangeSet, 
/**
 * 適用したあとに開く文書。何も開かなければ `None`。
 */
created: RelPath | null, 
/**
 * 人物を消すとき、その人物の名前を挙げているシーン。名前は書き換えない（知らせるだけ）。
 */
references: Array<SceneReference>, 
/**
 * 利用者への注意書き（「第 3 章は読めないため参照を確かめられませんでした」など）。
 */
notices: Array<string>, };
