// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";
import type { CharacterMeta } from "./CharacterMeta";
import type { NewScenePlan } from "./NewScenePlan";
import type { RelPath } from "./RelPath";
import type { SceneId } from "./SceneId";

/**
 * 構成に対する 1 つの操作。
 */
export type StructureEdit = { "kind": "add_character", 
/**
 * ID（ファイル名）。`None` か空白だけなら、読み（無ければ名前）からローマ字で決める。
 *
 * 文字列のまま受けて、使えるかどうかは変更案を作るときに確かめる
 * （使えない ID は、利用者が直せる入力の誤りとして知らせる）。
 */
id: string | null, 
/**
 * 項目。`order` が `None` なら、今の最大の次の番号（末尾）にする。
 */
meta: CharacterMeta, 
/**
 * 人物資料の本文。空でもよい（空なら、生成の工程に「人物資料」が取りかかれる工程として出る）。
 */
body: string, } | { "kind": "remove_character", 
/**
 * 消す人物資料。`characters/` 直下の Markdown。
 *
 * ID ではなくパスで指す。ファイル名が人物 ID の規則に合わない資料（手で足した `Rin.md` や `凛.md`）も
 * 目次に出るので、消せるようにするため。
 */
path: RelPath, } | { "kind": "add_world_document", 
/**
 * ファイル名（英小文字・数字・ハイフン。拡張子は付けない）。`None` なら題から決める。
 */
name: string | null, 
/**
 * 題。本文の先頭の見出しになる。
 */
title: string, 
/**
 * 本文。
 */
body: string, } | { "kind": "remove_world_document", 
/**
 * 消す資料。`world/` 直下の Markdown。
 */
path: RelPath, } | { "kind": "add_chapter", 
/**
 * この章の前に足す。`None` なら末尾。
 */
before: ChapterId | null, 
/**
 * 章題。
 */
title: string, 
/**
 * ストーリーライン（章立ての本文）。空でもよい。シーン構成は空で作る。
 */
storyline: string, } | { "kind": "remove_chapter", 
/**
 * 消す章。
 */
chapter: ChapterId, } | { "kind": "add_scene", 
/**
 * 足す章。
 */
chapter: ChapterId, 
/**
 * このシーンの前に足す。`None` なら章の末尾。
 */
before: SceneId | null, 
/**
 * 足すシーンの設計。
 */
scene: NewScenePlan, } | { "kind": "remove_scene", 
/**
 * 消すシーンのある章。
 */
chapter: ChapterId, 
/**
 * 消すシーン。
 */
scene: SceneId, };
