// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";
import type { CharacterId } from "./CharacterId";
import type { CharacterMeta } from "./CharacterMeta";
import type { NewScenePlan } from "./NewScenePlan";
import type { RelPath } from "./RelPath";
import type { SceneId } from "./SceneId";

/**
 * 構成に対する 1 つの操作。
 */
export type StructureEdit = { "kind": "add_character", 
/**
 * ID（ファイル名）。`None` なら、読み（無ければ名前）からローマ字で決める。
 */
id: CharacterId | null, 
/**
 * 項目。`order` が `None` なら、今の最大の次の番号（末尾）にする。
 */
meta: CharacterMeta, 
/**
 * 人物資料の本文。空でもよい（空なら、生成の工程に「人物資料」が取りかかれる工程として出る）。
 */
body: string, } | { "kind": "remove_character", 
/**
 * 消す人物。
 */
id: CharacterId, } | { "kind": "add_world_document", 
/**
 * ファイル名（英小文字・数字・ハイフン。拡張子は付けない）。`None` なら題から決める。
 */
name: string | null, 
/**
 * 題。本文の先頭の見出しになる。
 */
title: string, 
/**
 * 本文。
 */
body: string, } | { "kind": "remove_world_document", 
/**
 * 消す資料。`world/` 直下の Markdown。
 */
path: RelPath, } | { "kind": "add_scene", 
/**
 * 足す章。
 */
chapter: ChapterId, 
/**
 * このシーンの前に足す。`None` なら章の末尾。
 */
before: SceneId | null, 
/**
 * 足すシーンの設計。
 */
scene: NewScenePlan, } | { "kind": "remove_scene", 
/**
 * 消すシーンのある章。
 */
chapter: ChapterId, 
/**
 * 消すシーン。
 */
scene: SceneId, };
