// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChapterId } from "./ChapterId";
import type { CharacterId } from "./CharacterId";
import type { RelPath } from "./RelPath";
import type { SceneId } from "./SceneId";

/**
 * 1 回の「生成」で行う仕事。どのタスクも変更案（`ChangeSet`）を返し、ファイルは直接書き換えない。
 */
export type Task = { "kind": "concept" } | { "kind": "style" } | { "kind": "world" } | { "kind": "cast" } | { "kind": "character", id: CharacterId, } | { "kind": "synopsis" } | { "kind": "outline" } | { "kind": "scene_plan", chapter: ChapterId, } | { "kind": "draft", chapter: ChapterId, scene: SceneId, } | { "kind": "revise", path: RelPath, instruction: string, };
