// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 画面へ返すテキストファイル。[`kataribe_project::TextFile`] の `hash` を文字列にしたもの。
 */
export type TextFile = { content: string, 
/**
 * 読み込んだ時点の内容のハッシュ（16 進小文字）。上書き時の競合検出に使う。
 */
hash: string, };
