// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 本文の計数結果。
 */
export type TextStats = { 
/**
 * 本文の文字数（ルビの読み・空白・改行を除き、書記素クラスタ単位で数える）。
 */
chars: number, 
/**
 * 空行でない行の数。
 */
paragraphs: number, 
/**
 * 「または『で始まる行の数。
 */
dialogue_lines: number, 
/**
 * 400 字詰め原稿用紙換算の枚数。
 */
manuscript_pages: number, };
