// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { RelPath } from "./RelPath";

/**
 * ゴミ箱へ移すファイル。
 */
export type TrashedFile = { 
/**
 * 作品フォルダからの相対パス。
 */
path: RelPath, 
/**
 * 移す前の内容のハッシュ。適用時に、その後の編集と競合していないか確かめる。
 * テキストとして読めなかったファイルは `None`（適用できない）。
 */
base_hash: ContentHash | null, 
/**
 * 内容の文字数（ルビの読み・空白を除く）。何が失われるかを利用者に見せるため。
 */
chars: number, };
